### PR TITLE
Create instructions.md

### PR DESCRIPTION
**Pull request by Reconcyl**
Create a file for instruction listings

### CODE REVIEW

**Comment by SilversApprentice** [comment]
Most of it I was okay with, but I was confused as to why there were so many special characters(such as Greek characters and letters with symbols over them(which, _I know_, are used in different languages, but...)), and I was a little confused on how some of the commands would work, but _overall_ I think it's good

**Comment by Reconcyl** [comment]
The reason for all the strange characters is that I expected all lowercase letters to be reserved for variable names, so I use capital letters and weird unicode characters. Most can be typed using the option key on a Mac keyboard, but some cannot. This language is meant for compactness, not ease of use.

**Comment by Reconcyl** [comment]
A lot of these were borrowed from RiverScript.

**Comment by SilversApprentice** [comment]
We still need to be able to type it lmao

**Comment by Reconcyl** [comment]
Yeah, like I said most can be typed with the option key, and you can copy-paste from the documentation if you want. Our priority is short code, not usability, right?

**Comment by SilversApprentice** [comment]
Keep in mind that not everyone has the option key. While the alternative for windows users would be the alt key, it's still a bother to type. And yes, it's true that our priority is short code. However, we don't want it to be too frightening for the layman codegolfer. This being said, I do agree that it's a good start. I'll merge it.

**Comment by SilversApprentice** [comment]
Actually, I wanted to ask, why use '±' instead of just '-'?

**Pull request merged**
