### PR TITLE
Instruction list, character table, and Python3 parser

### PR DESCRIPTION
**Pull request by Reconcyl**
Instruction listings and a table for characters. We can define our own encoding like 05AB1E or Jelly, so I created a table for that.

### CODE REVIEW

**Comment by SilversApprentice** [comment]
There are still things that could be changed, but we can deal with those later. Is this ready to be merged?

**Comment by Reconcyl** [comment]
Yeah. By the way, is there a way to update an existing pull request? (I'm not very familiar with GitHub)

**Comment by Reconcyl** [comment]
Oh, it updates automatically? Great!

**Comment by Reconcyl** [comment]
I've now fixed all the bugs I could find with the Python parser, so it should be good to go!

**Comment by Reconcyl** [comment]
I don't understand your change to `parser.py`. Now the program is not able to distinguish between getting and setting a variable... Also, since we have 1-char var names, we have to change that as well.

**Comment by Reconcyl** [comment]
I am also confused about your changes to the variable getting/setting syntax in `instructions.md`. With your syntax I cannot see a way to set a variable to a value that is already on the stack. It is ambiguous whether to set a variable to the value on top of the stack, or push the variable onto the stack.

**Comment by SilversApprentice** [comment]
I'm confused as to why you're confused. `24a` sets the variable  `a` to equal `24`. `a` calls the variable `a`

**Comment by Reconcyl** [comment]
But what if I preformed some calculation and now had the value `24` on top of the stack, and I wanted to store that in `a`?

**Comment by SilversApprentice** [comment]
whatever you want to store in `a`, you type what you want to store and immediately write `a` after it

**Comment by Reconcyl** [comment]
So what if I had two values `a` and `b` and I wanted to add them together and store them in `c`? With my method it would be `ab+C`. With your method: First, I'd have to push both numbers onto the stack. I can't to `ab` because that would set `b` to `a`, so I'd have to do `a b`, with a space between them. Then, I could add them with `a b+`. But how would I store this new value in `c`? It seems like this method would not allow you to store any unknown value in a variable unless you had an explicit reference to the top of the stack (which we'll call `t`). So now this simple problem would have to be written as `a b+tc`.

**Comment by SilversApprentice** [comment]
no, with my method as well it would be `ab+c`...

**Comment by Reconcyl** [comment]
So I assume adding `a` and `b` and then pushing the value of `c` would be `ab+ c`?

**Comment by Reconcyl** [comment]
This seems like it would take more bytes. Why don't you like my version? It seems like it would be less ambiguous to have a different set of characters for getting variables...

**Comment by SilversApprentice** [comment]
What do you mean by pushing the value of c? I feel like I know this, but my mind is kinda fuzzy after walking around outside for two hours

**Comment by Reconcyl** [comment]
Let's say I just asked for user input twice and the user input was `2` and `3`. I added it together and stored it in `c`. Now `c` has a value of 5. The value stored in `c` is 5.

**Comment by Reconcyl** [comment]
If the variable `c` has a value of `5`, pushing the value of `c` would push `5`.

**Comment by SilversApprentice** [comment]
I see your point with the capitals now. I take back what I said before, the capitals would be better I guess.

**Comment by Reconcyl** [comment]
Do you have any other concerns? If not, can this be merged?

**Comment by SilversApprentice** [comment]
welp no not really I don't

**Pull request merged**
